### ISSUE TITLE
Include "host-functions" feature of ics23 under the features

### ISSUE THREAD

**Issue by Farhad-Shabani** [cosmos/ibc-proto-rs#108]
### Background

Needed in some places of `ics23_commitment` within `ibc-rs`. So then, we can completely move away from ics23 dependency there and only import ics23 types from `ibc-proto-rs`.

**Comment by romac** [comment]
I think it should be up to ibc-rs to depend on both inc-proto and ics23 and enable that feature for the latter. Verification of commitment proofs is imho not the responsibility of this crate and should be left up to the dépendants of this crate.

**Comment by Farhad-Shabani** [comment]
> I think it should be up to ibc-rs to depend on both inc-proto and ics23 and enable that feature for the latter. Verification of commitment proofs is imho not the responsibility of this crate and should be left up to the dépendants of this crate.

Very true, my bad! was looking at the `cosmos/ics23` as the only proto types' provider, and thought of the host-functions so. Thanks for pointing that out!

Though, to clear up the point of confusion. Apart from the proto types from the `ics23` crate, we can actually access [bunch of other types](https://github.com/cosmos/ics23/blob/master/rust/src/lib.rs#L24-L31) through the ibc-proto-rs. Perhaps, ideally, we should only re-export the proto types of ics23?

**Comment by romac** [comment]
> Though, to clear up the point of confusion. Apart from the proto types from the ics23 crate, we can actually access bunch of other types through the ibc-proto-rs. Perhaps, ideally, we should only re-export the proto types of ics23?

Good question! On one hand it's kinda handy to have these on hand for when the client code defines its own HostFunctionsProvider and therefore would not need to explicitly add in ics23 as a dependency with the host-functions feature enabled. On the other hand, as point out, it goes against the argument I was making above and conflates multiple concerns together.

In the end, I don't feel super strongly either way, but would slightly favor exporting only the protos and leaving verification up to the client.

Alternatively, we could split the protos out of ics23 and into their own crate and re export that only, but it's perhaps a bit overkill.

**Comment by Farhad-Shabani** [comment]
> In the end, I don't feel super strongly either way, but would slightly favor exporting only the protos and leaving verification up to the client.

👍🏻 

> Alternatively, we could split the protos out of ics23 and into their own crate and re export that only, but it's perhaps a bit overkill.

Yes, looks unnecessary right now. Maybe to keep it in mind for future improvements.
