### ISSUE TITLE
Update to Prost 0.12.0

### ISSUE THREAD

**Issue by hdevalence** [cosmos/ibc-proto-rs#145]
Hi, we'd like to migrate to Prost 0.12.0, but we need to have compatibility across all of our deps. Would it be possible to get an `ibc-proto-rs` release using `prost` `0.12.0`?

**Comment by tony-iqlusion** [comment]
Notably this release includes a `Name` trait which can be used to compute the `type_url` for `Any` types, when impl'd for a particular `Message` type: https://docs.rs/prost/latest/prost/trait.Name.html#method.type_url

Unfortunately there isn't yet `prost-build` automation for generating impls of that trait, but hopefully it's coming soon.

**Comment by hdevalence** [comment]
Yes, that's the big reason we're interested in it -- we had our own version of that trait, reorganized all our protos, and are hoping to avoid having to go and update all the type urls manually: https://github.com/penumbra-zone/penumbra/pull/3077#issuecomment-1730866734

**Comment by romac** [comment]
I'll get to this right after I publish v0.36.0.
