### ISSUE TITLE
Docs build does not show on docs.rs

### ISSUE THREAD

**Issue by conorsch** [cosmos/ibc-proto-rs#154]
As of the v0.37.0 release, the "latest" docs.rs URLs for `ibc-proto` don't work:

```
❯ curl -sI https://docs.rs/ibc-proto/latest/ibc_proto/ | head -n1
HTTP/2 404 
```

The prior version still works, though:

```
❯ curl -sI https://docs.rs/ibc-proto/0.36.1/ibc_proto/ | head -n1
HTTP/2 200 
❯ curl -sI https://docs.rs/ibc-proto/0.36.1/ibc_proto/ibc/core/connection/v1/query_client/index.html  | head -n1 
HTTP/2 200 
```

It'd be great to have the "latest" URLs working again.

**Comment by romac** [comment]
Sounds like an issue with docs.rs given that the doc build seems to have succeeded: https://docs.rs/crate/ibc-proto/latest/builds

We'll see what we can do!

**Comment by romac** [comment]
In the meantime, since the docs do actually build, you can access them locally by cloning this repo and running `cargo doc --open`

**Comment by romac** [comment]
Opened an issue on the docs.rs repo: https://github.com/rust-lang/docs.rs/issues/2247

**Comment by romac** [comment]
Fixed: https://docs.rs/ibc-proto/0.37.0/ibc_proto/
