### ISSUE TITLE
Should I abandon `cosmos-sdk-proto` and point people at `ibc-proto` instead?

### ISSUE THREAD

**Issue by tony-iqlusion** [cosmos/ibc-proto-rs#182]
The two projects duplicate each others' functionality, but `ibc-proto` seems more mature at this point.

I find the whole situation a bit confusing and frustrating: `ibc-proto` has a much bigger scope than just IBC, and is instead a full Cosmos SDK Protobuf library.

`cosmos-sdk-proto` also has more downloads and a "Used by" count of 661 (whereas that number isn't populated for `ibc-proto-rs` for whatever reason). Just by virtue of its name it's more discoverable.

But I find duplication of effort to be incredibly demotivating.

**Comment by romac** [comment]
Hi Tony! Thanks for starting this discussion, I absolutely agree that the current situation is really subpar and we should aim to improve it.

How about I spend some time this week investigating whether we can deduplicate work by:
* Removing the Cosmos SDK protos from `ibc-proto` and instead use `cosmos-sdk-proto` as external definition for those.
* Removing the IBC protos from `cosmos-sdk-proto` and advise users to depend explicitly on `ibc-proto` if they need those

Would that seem like a good course of action to you? Is there something else you think should be done to remediate the current situation?

**Comment by tony-iqlusion** [comment]
That approach seems fine to me.

I think ideally they'd be in the same repo to synchronize changes, but if that's the direction you'd like to go, I'm happy to work toward that in whatever manner.

**Comment by tony-iqlusion** [comment]
With #187 open I'll go ahead and close this

**Comment by romac** [comment]
👍 Shall I open a PR on cosmos-rust so we can discuss there how best to proceed with all this?

**Comment by tony-iqlusion** [comment]
Yep, absolutely
